// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKpeEVvHfplKVsVJCZUGAUwCqxmmCNssg',
    appId: '1:310006072367:web:208cc911ea3b08c82832da',
    messagingSenderId: '310006072367',
    projectId: 'borrow-booksy',
    authDomain: 'borrow-booksy.firebaseapp.com',
    storageBucket: 'borrow-booksy.firebasestorage.app',
    measurementId: 'G-9D5LPF1F3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTpEvC7H-AxVXzo7yR1VHg8PDfYKU5wBs',
    appId: '1:310006072367:android:4f63d40653babb562832da',
    messagingSenderId: '310006072367',
    projectId: 'borrow-booksy',
    storageBucket: 'borrow-booksy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0dNfTk1myBs7dRoLclpY7T7qZSxiMzjs',
    appId: '1:310006072367:ios:95be0ca7ec04faaf2832da',
    messagingSenderId: '310006072367',
    projectId: 'borrow-booksy',
    storageBucket: 'borrow-booksy.firebasestorage.app',
    iosBundleId: 'com.example.borrowBooksy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0dNfTk1myBs7dRoLclpY7T7qZSxiMzjs',
    appId: '1:310006072367:ios:95be0ca7ec04faaf2832da',
    messagingSenderId: '310006072367',
    projectId: 'borrow-booksy',
    storageBucket: 'borrow-booksy.firebasestorage.app',
    iosBundleId: 'com.example.borrowBooksy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKpeEVvHfplKVsVJCZUGAUwCqxmmCNssg',
    appId: '1:310006072367:web:c7c7692675edacd62832da',
    messagingSenderId: '310006072367',
    projectId: 'borrow-booksy',
    authDomain: 'borrow-booksy.firebaseapp.com',
    storageBucket: 'borrow-booksy.firebasestorage.app',
    measurementId: 'G-XCBK68XVBB',
  );
}
